base_url = "https://esther-son.github.io/insight"
title = "InSight"
description = "Stock & News Analysis"
compile_sass = false
build_search_index = false
minify_html = false

[markdown]
highlight_code = false

[extra]
github_username = "Esther-Son"
author = "Esther-Son"
